fix: correct user-facing English messages

diff --git a/bin/nscde_fvwmclnt.in b/bin/nscde_fvwmclnt.in
--- a/bin/nscde_fvwmclnt.in
+++ b/bin/nscde_fvwmclnt.in
@@ -50,6 +50,5 @@ fi
 if [ "x$FVWM_CLNT" != "x" ]; then
    exec $FVWM_CLNT "$@"
 else
-   echo "ERROR: Cannot find suitable FvwmCommand for your setup." >&2
+   echo "Error: cannot find a suitable FvwmCommand for this setup." >&2
 fi
-
