fix: improve helper diagnostics and usage text

diff --git a/nscde_tools/acpimgr.in b/nscde_tools/acpimgr.in
--- a/nscde_tools/acpimgr.in
+++ b/nscde_tools/acpimgr.in
@@ -53,7 +53,7 @@ elif [ "$OS" == "OpenBSD" ]; then
 else
    Opmode=$2
    if [ "x$Opmode" == "x" ]; then
-      echo "Error: Unknown ACPI operation mode."
+      echo "Error: unknown ACPI operation mode."
       exit 4
    fi
 fi
@@ -86,7 +86,7 @@ function hibernate
    elif [ "$Opmode" == "sunos" ]; then
       pfexec sys-suspend -n
    elif [ "$Opmode" == "netbsd" ]; then
-      echo "Notice: Hibernate to disk is not supported on NetBSD."
+      echo "Notice: hibernation to disk is not supported on NetBSD."
    elif [ "$Opmode" == "openbsd" ]; then
       /usr/sbin/apm -Z
    fi
@@ -99,13 +99,13 @@ function hybrid_suspend
    elif [ "$Opmode" == "systemd" ]; then
       systemctl hybrid-sleep -i
    elif [ "$Opmode" == "acpiconf" ]; then
-      echo "Not available on $OS" >&2
+      echo "Not available on $OS." >&2
    elif [ "$Opmode" == "sunos" ]; then
       pfexec sys-suspend -n
    elif [ "$Opmode" == "netbsd" ]; then
-      echo "Notice: Hybrid suspend is not supported on NetBSD."
+      echo "Notice: hybrid suspend is not supported on NetBSD."
    elif [ "$Opmode" == "openbsd" ]; then
-      echo "Notice: Hybrid suspend is not supported on OpenBSD."
+      echo "Notice: hybrid suspend is not supported on OpenBSD."
    fi
 }
 
@@ -182,4 +182,3 @@ case $Action in
       usage
    ;;
 esac
-
diff --git a/nscde_tools/get_logical_screens.in b/nscde_tools/get_logical_screens.in
--- a/nscde_tools/get_logical_screens.in
+++ b/nscde_tools/get_logical_screens.in
@@ -34,7 +34,7 @@ function defaultcf
 # Without xrandr(1) we cannot continue.
 type -qp xrandr
 if (($? != 0)); then
-   echo "${0##*/}: xrandr command is not available in PATH. Setting default one monitor setup." >&2
+   echo "${0##*/}: xrandr is not available in PATH; using a single-monitor setup." >&2
    defaultcf
    exit 0
 fi
@@ -46,7 +46,7 @@ mdata=$(xrandr --listmonitors)
 # for this Xinerama/SLS support.
 screencnt=$(echo "$xdata" | wc -l)
 if (($screencnt > 1)); then
-   echo "${0##*/}: More than one local screen handling is not yet tested and hence not supported." >&2
+   echo "${0##*/}: multiple local X screens are not currently supported." >&2
    defaultcf
    exit 0
 fi
@@ -81,7 +81,7 @@ if (($? == 0)); then
       echo "InfoStoreAdd lscrn.cnt $moncnt"
    fi
 else
-   echo "${0##*/}: Error in handling monitor count: \"$moncnt\""
+   echo "${0##*/}: invalid monitor count: $moncnt."
    defaultcf
    exit 0
 fi
@@ -133,7 +133,7 @@ do
          rootmenudata=$(@ECHONE@ "$rootmenudata\nAddToMenu m_SlsMoveAll \"Move To Logical Screen: &${scnum} ($[infostore.lscrn.${scrvar}.name]) ...\"           All MoveToScreen ${scrvar}")
       fi
    else
-      echo "${0##*/}: Error in handling monitor $mname width: (\"$scwidth\") or height (\"$scheight\")" >&2
+      echo "${0##*/}: invalid geometry for monitor $mname (width: $scwidth; height: $scheight)." >&2
       defaultcf
       break
    fi
@@ -216,4 +216,3 @@ if [ "x${check_fvwm3}" == "x1" ] ; then
       done < "$UserBackdropsFile"
    fi
 fi
-
diff --git a/nscde_tools/subpanel_menuitem_props.in b/nscde_tools/subpanel_menuitem_props.in
--- a/nscde_tools/subpanel_menuitem_props.in
+++ b/nscde_tools/subpanel_menuitem_props.in
@@ -64,14 +64,14 @@ function subpanels_file_tstamp
    REGEN=0
    if [[ -r "$FVWM_USERDIR/Subpanels.actions" && -r "$FVWM_USERDIR/Subpanels.fvwm2.fvwmgen" ]]; then
       if [ "$FVWM_USERDIR/Subpanels.actions" -nt "$FVWM_USERDIR/Subpanels.fvwm2.fvwmgen" ]; then
-         echo "File $FVWM_USERDIR/Subpanels.actions is newer than $FVWM_USERDIR/Subpanels.fvwm2.fvwmgen ... regenerating last one." >&2
+         echo "$FVWM_USERDIR/Subpanels.actions is newer than $FVWM_USERDIR/Subpanels.fvwm2.fvwmgen; regenerating the latter." >&2
          $NSCDE_TOOLSDIR/generate_subpanels -w > $FVWM_USERDIR/Subpanels.fvwm2.fvwmgen
          REGEN=1
       fi
    fi
    if [[ -r "$FVWM_USERDIR/Subpanels.actions" && -r "$FVWM_USERDIR/Subpanels.fvwm3.fvwmgen" ]]; then
       if [ "$FVWM_USERDIR/Subpanels.actions" -nt "$FVWM_USERDIR/Subpanels.fvwm3.fvwmgen" ]; then
-         echo "File $FVWM_USERDIR/Subpanels.actions is newer than $FVWM_USERDIR/Subpanels.fvwm3.fvwmgen ... regenerating last one." >&2
+         echo "$FVWM_USERDIR/Subpanels.actions is newer than $FVWM_USERDIR/Subpanels.fvwm3.fvwmgen; regenerating the latter." >&2
          $NSCDE_TOOLSDIR/generate_subpanels -f > $FVWM_USERDIR/Subpanels.fvwm3.fvwmgen
          REGEN=1
       fi
@@ -301,14 +301,14 @@ function manage_entry
             $NSCDE_ROOT/bin/nscde_fvwmclnt "f_Notifier \"Subpanel Properties\" \"Dismiss\" \"NsCDE/Error.xpm\" \
                         \"$[gt.Action for item] '$TITLE' $[gt.not performed on Subpanel] $subpid. $[gt.Errors found in] $tmpfile.\""
          else
-            echo "Action for item $TITLE not performed on Subpanel $subpid. Errors in $tmpfile found." >&2
+            echo "Action for item $TITLE was not performed on subpanel $subpid; errors were written to $tmpfile." >&2
          fi
          exit 2
       fi
    fi
 
    if [ -f "$tmpfile" ]; then
-      echo "Removing stale tmp file $tmpfile" >&2
+      echo "Removing stale temporary file $tmpfile." >&2
       rm -f "$tmpfile"
    fi
 }
@@ -406,7 +406,7 @@ function copy_to_main_panel
       entry_to_copy=$(egrep -h "^S${subpid},ENTRY,*" "$NSCDE_DATADIR/defaults/Subpanels.actions" | sed -n "${entryid}p")
    fi
    if [ "x$entry_to_copy" == "x" ]; then
-      echo "ERROR: subpanel_menuitem_props (copy_to_main_panel): internal error. No entry in system Subpanels.actons file."
+      echo "Error: subpanel_menuitem_props (copy_to_main_panel): no entry in the system Subpanels.actions file."
       exit 10
    fi
    echo "$entry_to_copy" | tail -1 | while IFS="," read smark emark title type icon cmd
@@ -414,7 +414,7 @@ function copy_to_main_panel
       for content in "$title" "$icon" "$cmd"
       do
          if [ "x$content" == "x" ]; then
-            echo "ERROR: subpanel_menuitem_props (copy_to_main_panel): empty title, icon or command definition."
+            echo "Error: subpanel_menuitem_props (copy_to_main_panel): the title, icon, or command is empty."
             exit 10
          fi
       done
@@ -441,7 +441,7 @@ function copy_to_main_panel
 
       # Try find_appropriate_icon with different extensions.
       if (($ENOICON == 1)); then
-         echo "Trying heuristics with icon extension formats while searching for an icon ..."
+         echo "Trying alternate file extensions while searching for an icon ..."
          export ENOICON=0
          case "$icon_ext" in
          'png')
@@ -744,4 +744,3 @@ do
       ;;
    esac
 done
-
diff --git a/nscde_tools/xdowrapper.in b/nscde_tools/xdowrapper.in
--- a/nscde_tools/xdowrapper.in
+++ b/nscde_tools/xdowrapper.in
@@ -11,7 +11,7 @@
 
 type -qp xdotool
 if (($? != 0)); then
-   echo "No xdotool found. Exiting." >&2
+   echo "xdotool was not found. Exiting." >&2
    exit 1
 fi
 
@@ -49,4 +49,3 @@ do
 
    (( cnt = cnt + 1 ))
 done
-
