i18n: add gettext support to helper tools

diff --git a/nscde_tools/acpimgr.in b/nscde_tools/acpimgr.in
--- a/nscde_tools/acpimgr.in
+++ b/nscde_tools/acpimgr.in
@@ -6,6 +6,19 @@
 # Licence: GPLv3
 #
 
+TEXTDOMAINDIR="${NSCDE_DATADIR:-@NSCDE_DATADIR@}/../locale"
+TEXTDOMAIN="nscde-tools"
+export TEXTDOMAINDIR TEXTDOMAIN
+
+function nscde_gettext
+{
+   if whence -q gettext; then
+      gettext "$1"
+   else
+      printf '%s' "$1"
+   fi
+}
+
 PATH="/sbin:/usr/sbin:/usr/local/sbin:/bin:/usr/bin:/usr/local/bin:$PATH"
 Action=$1
 
@@ -53,7 +66,7 @@ elif [ "$OS" == "OpenBSD" ]; then
 else
    Opmode=$2
    if [ "x$Opmode" == "x" ]; then
-      echo "Error: unknown ACPI operation mode."
+      printf '%s\n' "$(nscde_gettext 'Error: unknown ACPI operation mode.')"
       exit 4
    fi
 fi
@@ -86,7 +99,7 @@ function hibernate
    elif [ "$Opmode" == "sunos" ]; then
       pfexec sys-suspend -n
    elif [ "$Opmode" == "netbsd" ]; then
-      echo "Notice: hibernation to disk is not supported on NetBSD."
+      printf '%s\n' "$(nscde_gettext 'Notice: hibernation to disk is not supported on NetBSD.')"
    elif [ "$Opmode" == "openbsd" ]; then
       /usr/sbin/apm -Z
    fi
@@ -99,13 +112,13 @@ function hybrid_suspend
    elif [ "$Opmode" == "systemd" ]; then
       systemctl hybrid-sleep -i
    elif [ "$Opmode" == "acpiconf" ]; then
-      echo "Not available on $OS." >&2
+      printf "$(nscde_gettext 'Not available on %s.')\n" "$OS" >&2
    elif [ "$Opmode" == "sunos" ]; then
       pfexec sys-suspend -n
    elif [ "$Opmode" == "netbsd" ]; then
-      echo "Notice: hybrid suspend is not supported on NetBSD."
+      printf '%s\n' "$(nscde_gettext 'Notice: hybrid suspend is not supported on NetBSD.')"
    elif [ "$Opmode" == "openbsd" ]; then
-      echo "Notice: hybrid suspend is not supported on OpenBSD."
+      printf '%s\n' "$(nscde_gettext 'Notice: hybrid suspend is not supported on OpenBSD.')"
    fi
 }
 
@@ -153,7 +166,7 @@ function f_reboot
 
 function usage
 {
-   echo "Usage: ${0##*/} [ suspend | hibernate | hybrid-suspend | poweroff | reboot ] [ opmode ]"
+   printf "$(nscde_gettext 'Usage: %s [ suspend | hibernate | hybrid-suspend | poweroff | reboot ] [ opmode ]')\n" "${0##*/}"
    exit 0
 }
 
diff --git a/nscde_tools/get_logical_screens.in b/nscde_tools/get_logical_screens.in
--- a/nscde_tools/get_logical_screens.in
+++ b/nscde_tools/get_logical_screens.in
@@ -11,6 +11,19 @@
 # and export this as FVWM infostore variables for use in FVWM
 # On a cloned display, this will simply return one global size
 
+TEXTDOMAINDIR="${NSCDE_DATADIR:-@NSCDE_DATADIR@}/../locale"
+TEXTDOMAIN="nscde-tools"
+export TEXTDOMAINDIR TEXTDOMAIN
+
+function nscde_gettext
+{
+   if whence -q gettext; then
+      gettext "$1"
+   else
+      printf '%s' "$1"
+   fi
+}
+
 IFS=" "
 check_fvwm3=${FVWM_IS_FVWM3}
 
@@ -34,7 +47,7 @@ function defaultcf
 # Without xrandr(1) we cannot continue.
 type -qp xrandr
 if (($? != 0)); then
-   echo "${0##*/}: xrandr is not available in PATH; using a single-monitor setup." >&2
+   printf "$(nscde_gettext '%s: xrandr is not available in PATH; using a single-monitor setup.')\n" "${0##*/}" >&2
    defaultcf
    exit 0
 fi
@@ -46,7 +59,7 @@ mdata=$(xrandr --listmonitors)
 # for this Xinerama/SLS support.
 screencnt=$(echo "$xdata" | wc -l)
 if (($screencnt > 1)); then
-   echo "${0##*/}: multiple local X screens are not currently supported." >&2
+   printf "$(nscde_gettext '%s: multiple local X screens are not currently supported.')\n" "${0##*/}" >&2
    defaultcf
    exit 0
 fi
@@ -81,7 +94,7 @@ if (($? == 0)); then
       echo "InfoStoreAdd lscrn.cnt $moncnt"
    fi
 else
-   echo "${0##*/}: invalid monitor count: $moncnt."
+   printf "$(nscde_gettext '%s: invalid monitor count: %s.')\n" "${0##*/}" "$moncnt"
    defaultcf
    exit 0
 fi
@@ -130,10 +143,10 @@ do
          echo "InfoStoreAdd lscrn.${scrvar}.pos.x $scpos_x"
          echo "InfoStoreAdd lscrn.${scrvar}.pos.y $scpos_y"
          echo "InfoStoreAdd lscrn.${scrvar}.name $mname"
-         rootmenudata=$(@ECHONE@ "$rootmenudata\nAddToMenu m_SlsMoveAll \"Move To Logical Screen: &${scnum} ($[infostore.lscrn.${scrvar}.name]) ...\"           All MoveToScreen ${scrvar}")
+         rootmenudata=$(@ECHONE@ "$rootmenudata\nAddToMenu m_SlsMoveAll \"\$[gt.Move To Logical Screen:] &${scnum} ($[infostore.lscrn.${scrvar}.name]) ...\"           All MoveToScreen ${scrvar}")
       fi
    else
-      echo "${0##*/}: invalid geometry for monitor $mname (width: $scwidth; height: $scheight)." >&2
+      printf "$(nscde_gettext '%s: invalid geometry for monitor %s (width: %s; height: %s).')\n" "${0##*/}" "$mname" "$scwidth" "$scheight" >&2
       defaultcf
       break
    fi
@@ -144,7 +157,7 @@ if (($scpos_sum > 0)); then
    echo ""
    echo "DestroyMenu m_SlsMoveAll"
    echo "AddToMenu m_SlsMoveAll"
-   echo "+ \"&Move All Windows To This Screen\"            f_MoveAllToThisScreen"
+   echo '+ "$[gt.&Move All Windows To This Screen]"            f_MoveAllToThisScreen'
    echo "+ \"\" Nop"
    echo "$rootmenudata" | egrep -v '^$'
 
diff --git a/nscde_tools/subpanel_menuitem_props.in b/nscde_tools/subpanel_menuitem_props.in
--- a/nscde_tools/subpanel_menuitem_props.in
+++ b/nscde_tools/subpanel_menuitem_props.in
@@ -6,6 +6,19 @@
 # Licence: GPLv3
 #
 
+TEXTDOMAINDIR="${NSCDE_DATADIR:-@NSCDE_DATADIR@}/../locale"
+TEXTDOMAIN="nscde-tools"
+export TEXTDOMAINDIR TEXTDOMAIN
+
+function nscde_gettext
+{
+   if whence -q gettext; then
+      gettext "$1"
+   else
+      printf '%s' "$1"
+   fi
+}
+
 # Function: examine_entrypart
 # Purpose: detect and count missing
 # entries until next valid one
@@ -64,14 +77,14 @@ function subpanels_file_tstamp
    REGEN=0
    if [[ -r "$FVWM_USERDIR/Subpanels.actions" && -r "$FVWM_USERDIR/Subpanels.fvwm2.fvwmgen" ]]; then
       if [ "$FVWM_USERDIR/Subpanels.actions" -nt "$FVWM_USERDIR/Subpanels.fvwm2.fvwmgen" ]; then
-         echo "$FVWM_USERDIR/Subpanels.actions is newer than $FVWM_USERDIR/Subpanels.fvwm2.fvwmgen; regenerating the latter." >&2
+         printf "$(nscde_gettext '%s is newer than %s; regenerating the latter.')\n" "$FVWM_USERDIR/Subpanels.actions" "$FVWM_USERDIR/Subpanels.fvwm2.fvwmgen" >&2
          $NSCDE_TOOLSDIR/generate_subpanels -w > $FVWM_USERDIR/Subpanels.fvwm2.fvwmgen
          REGEN=1
       fi
    fi
    if [[ -r "$FVWM_USERDIR/Subpanels.actions" && -r "$FVWM_USERDIR/Subpanels.fvwm3.fvwmgen" ]]; then
       if [ "$FVWM_USERDIR/Subpanels.actions" -nt "$FVWM_USERDIR/Subpanels.fvwm3.fvwmgen" ]; then
-         echo "$FVWM_USERDIR/Subpanels.actions is newer than $FVWM_USERDIR/Subpanels.fvwm3.fvwmgen; regenerating the latter." >&2
+         printf "$(nscde_gettext '%s is newer than %s; regenerating the latter.')\n" "$FVWM_USERDIR/Subpanels.actions" "$FVWM_USERDIR/Subpanels.fvwm3.fvwmgen" >&2
          $NSCDE_TOOLSDIR/generate_subpanels -f > $FVWM_USERDIR/Subpanels.fvwm3.fvwmgen
          REGEN=1
       fi
@@ -301,14 +314,14 @@ function manage_entry
             $NSCDE_ROOT/bin/nscde_fvwmclnt "f_Notifier \"Subpanel Properties\" \"Dismiss\" \"NsCDE/Error.xpm\" \
                         \"$[gt.Action for item] '$TITLE' $[gt.not performed on Subpanel] $subpid. $[gt.Errors found in] $tmpfile.\""
          else
-            echo "Action for item $TITLE was not performed on subpanel $subpid; errors were written to $tmpfile." >&2
+            printf "$(nscde_gettext 'Action for item %s was not performed on subpanel %s; errors were written to %s.')\n" "$TITLE" "$subpid" "$tmpfile" >&2
          fi
          exit 2
       fi
    fi
 
    if [ -f "$tmpfile" ]; then
-      echo "Removing stale temporary file $tmpfile." >&2
+      printf "$(nscde_gettext 'Removing stale temporary file %s.')\n" "$tmpfile" >&2
       rm -f "$tmpfile"
    fi
 }
@@ -406,7 +419,7 @@ function copy_to_main_panel
       entry_to_copy=$(egrep -h "^S${subpid},ENTRY,*" "$NSCDE_DATADIR/defaults/Subpanels.actions" | sed -n "${entryid}p")
    fi
    if [ "x$entry_to_copy" == "x" ]; then
-      echo "Error: subpanel_menuitem_props (copy_to_main_panel): no entry in the system Subpanels.actions file."
+      printf '%s\n' "$(nscde_gettext 'Error: subpanel_menuitem_props (copy_to_main_panel): no entry in the system Subpanels.actions file.')"
       exit 10
    fi
    echo "$entry_to_copy" | tail -1 | while IFS="," read smark emark title type icon cmd
@@ -414,7 +427,7 @@ function copy_to_main_panel
       for content in "$title" "$icon" "$cmd"
       do
          if [ "x$content" == "x" ]; then
-            echo "Error: subpanel_menuitem_props (copy_to_main_panel): the title, icon, or command is empty."
+            printf '%s\n' "$(nscde_gettext 'Error: subpanel_menuitem_props (copy_to_main_panel): the title, icon, or command is empty.')"
             exit 10
          fi
       done
@@ -441,7 +454,7 @@ function copy_to_main_panel
 
       # Try find_appropriate_icon with different extensions.
       if (($ENOICON == 1)); then
-         echo "Trying alternate file extensions while searching for an icon ..."
+         printf '%s\n' "$(nscde_gettext 'Trying alternate file extensions while searching for an icon ...')"
          export ENOICON=0
          case "$icon_ext" in
          'png')
@@ -693,7 +706,7 @@ function delete_confirm
 {
    if [[ -n $DISPLAY ]]; then
       $NSCDE_ROOT/bin/nscde_fvwmclnt "f_RunQuickScriptDialog ActionForm \
-                   \"$[gt.Delete item] \\\"$TITLE\\\" $[gt.from the subpanel] ${subpid}?\" \
+                   \"$[gt.Delete item] \\\"$TITLE\\\"? $[gt.Subpanel]: ${subpid}.\" \
                    $[gt.Yes] $[gt.No] \"$[gt.Confirm Entry Deletion]\" \
                    \"f_DeleteFromSubpanel $subpid $entryid\" Nop"
    fi
